"""fonts.py — self-hosted font emitter (BUILD-ARCH §4 insertion point 2).

Emits css/fonts.css: @font-face rules pointing at css/fonts/*.woff2.
The woff2 files are pre-subsetted offline (pyftsubset / fonttools) and
committed to css/fonts/. They never enter the build path.

Families (from variables.yaml typography.fonts, locked):
  Tagesschrift    — h1           (wt 400 normal)
  Walter Turncoat — h2-h6        (wt 400 normal)
  Overlock        — body         (wt 400 normal, 700 normal, 400 italic)
  Protest Revolution — special   (wt 400 normal)

Preload targets: tagesschrift-regular + overlock-regular (above-the-fold).
These are injected by builder_common.head_block() — not here.

Subset unicode ranges:
  Standard (Tagesschrift, Walter Turncoat, Overlock):
    U+0020-007E  Basic Latin
    U+00A0-00FF  Latin-1 Supplement
    U+0100-017F  Latin Extended-A (covers ē etc.)
    U+2013-2014  En/em dash
    U+2018-201F  Curly single/double quotes
    U+2022       Bullet
    U+2026       Ellipsis
  Narrow (Protest Revolution — all special-block text is ASCII English):
    U+0020-007E, U+00A0, U+2013-2014, U+2018-201F, U+2022, U+2026
"""

_LATIN_RANGE = (
    'U+0020-007E, U+00A0-00FF, U+0100-017F, '
    'U+2013-2014, U+2018-201F, U+2022, U+2026'
)
_ASCII_RANGE = 'U+0020-007E, U+00A0, U+2013-2014, U+2018-201F, U+2022, U+2026'

# (family, weight, style, filename, unicode-range)
_FACES = [
    ('Tagesschrift',      '400', 'normal', 'tagesschrift-regular.woff2',      _LATIN_RANGE),
    ('Walter Turncoat',   '400', 'normal', 'walter-turncoat-regular.woff2',   _LATIN_RANGE),
    ('Overlock',          '400', 'normal', 'overlock-regular.woff2',           _LATIN_RANGE),
    ('Overlock',          '700', 'normal', 'overlock-bold.woff2',              _LATIN_RANGE),
    ('Overlock',          '400', 'italic', 'overlock-italic.woff2',            _LATIN_RANGE),
    ('Protest Revolution','400', 'normal', 'protest-revolution-regular.woff2', _ASCII_RANGE),
]


def fonts_css():
    """Return the full content of css/fonts.css."""
    lines = ['/* AUTO-GENERATED by builders/fonts.py — do not edit. */']
    for family, weight, style, fname, urange in _FACES:
        lines.append(
            f"\n@font-face {{\n"
            f"  font-family: '{family}';\n"
            f"  src: url('fonts/{fname}') format('woff2');\n"
            f"  font-weight: {weight};\n"
            f"  font-style: {style};\n"
            f"  font-display: swap;\n"
            f"  unicode-range: {urange};\n"
            f"}}"
        )
    return '\n'.join(lines) + '\n'


def build(unit, root):
    unit.output.parent.mkdir(parents=True, exist_ok=True)
    css = fonts_css()
    unit.output.write_text(css, encoding='utf-8')
    print(f'Wrote {unit.output}  ({len(css):,} chars)')
