#!/usr/bin/env python3
"""planter-extract.py — regenerate vine-decor.svg from planter source SVGs.

Phase 2.5.3/4. Extracts the white-line "Shape" layer skeletons (statics /
geometrics / organics label groups) from two jl-site-planter*.svg files and
emits Media/SVG-Assets/vine-decor.svg: six <symbol>s (per corner: -sta, -geo,
-org) consumed by builder_common.vine_decor() as stacked dual-layer <use>
(white line + offset shimmer "drop shadow" — the styling pattern shared by
the critters/separators: Shape layer on top, gradient copy behind).

The Glow layers of the planter sources are NOT extracted: they carry
feGaussianBlur, which is forbidden on animated decor. The shimmer layer is
recreated at the host as an offset duplicate <use> stroked with the rotating
shimmer gradients (resolved in the host document, so the rAF reaches them).

Cleaning per element:
  - inkscape:/sodipodi: attributes and id= dropped (no internal references)
  - stroke colour, stroke-dasharray/-dashoffset dropped from style
    (host <use> sets stroke; dash comes from the growth animation)
  - display/opacity:1/paint-order noise dropped; fills + widths + caps kept
  - pathLength="100" injected on path/circle/ellipse/rect so the one
    stroke-dashoffset:100→0 rule draws every element uniformly

Usage: python3 Toolbox/Python/planter-extract.py            # default combo [3,1]
       python3 Toolbox/Python/planter-extract.py 2 1        # BL=planter2 BR=planter1
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SVG_DIR = ROOT / 'Media' / 'SVG-Assets'

LAYER_LABELS = [('sta', 'statics'), ('geo', 'geometrics'), ('org', 'organics')]

KEEP_DECLS = {
    'fill', 'fill-rule', 'stroke-width', 'stroke-linecap',
    'stroke-linejoin', 'stroke-miterlimit',
}


def balanced_group(text, label):
    """Return the full <g ...>...</g> subtree whose tag carries
    inkscape:label="<label>" (exact match)."""
    m = re.search(rf'<g\b[^>]*inkscape:label="{label}"[^>]*>', text)
    if not m:
        return None
    start = m.start()
    depth = 0
    for t in re.finditer(r'<g\b[^>]*>|</g>', text[start:]):
        depth += 1 if t.group(0).startswith('<g') else -1
        if depth == 0:
            return text[start:start + t.end()]
    return None


def clean_style(style):
    out = []
    for decl in style.split(';'):
        if ':' not in decl:
            continue
        k, v = (s.strip() for s in decl.split(':', 1))
        if k in KEEP_DECLS:
            out.append(f'{k}:{v}')
        elif k == 'opacity' and v not in ('1', '1.0'):
            out.append(f'{k}:{v}')
        # stroke colour / dasharray / dashoffset / display / *-opacity:1 /
        # paint-order / -inkscape-* are dropped
    return ';'.join(out)


def clean_subtree(sub):
    # drop editor-namespace attributes and ids
    sub = re.sub(r'\s+(?:inkscape|sodipodi):[a-zA-Z-]+="[^"]*"', '', sub)
    sub = re.sub(r'\s+id="[^"]*"', '', sub)

    def fix_elem(m):
        elem = m.group(0)
        sm = re.search(r'style="([^"]*)"', elem)
        if sm:
            cleaned = clean_style(sm.group(1))
            elem = (elem.replace(sm.group(0), f'style="{cleaned}"')
                    if cleaned else elem.replace(' ' + sm.group(0), ''))
        if (elem.startswith(('<path', '<circle', '<ellipse', '<rect'))
                and 'pathLength' not in elem):
            elem = re.sub(r'(/?>)$', r' pathLength="100"\1', elem)
        return elem

    sub = re.sub(r'<(?:g|path|circle|ellipse|rect)\b[^>]*/?>', fix_elem, sub)
    sub = re.sub(r'[ \t]+\n', '\n', sub)
    sub = re.sub(r'\n\s*\n', '\n', sub)
    return sub.strip()


def extract(planter_n, corner):
    path = SVG_DIR / f'jl-site-planter{planter_n}.svg'
    text = path.read_text(encoding='utf-8')
    vb = re.search(r'viewBox="([^"]+)"', text).group(1)
    # Shape subtree only (the white-line layer; Glow is regenerated at host)
    shape = balanced_group(text, 'Shape')
    if shape is None:
        sys.exit(f'no Shape layer in {path.name}')
    symbols = []
    for short, label in LAYER_LABELS:
        sub = balanced_group(shape, label)
        if sub is None:
            print(f'  {path.name}: no {label} layer — skipped')
            continue
        symbols.append(
            f'<symbol id="vine-{corner}-{short}" viewBox="0 0 {vb.split()[2]} {vb.split()[3]}">\n'
            f'{clean_subtree(sub)}\n</symbol>'
        )
    print(f'  {path.name} → vine-{corner}-* ({len(symbols)} symbols, viewBox {vb})')
    return vb, symbols


def main():
    bl_n = sys.argv[1] if len(sys.argv) > 1 else '3'
    br_n = sys.argv[2] if len(sys.argv) > 2 else '1'
    bl_vb, bl_syms = extract(bl_n, 'bl')
    br_vb, br_syms = extract(br_n, 'br')
    body = '\n\n'.join(bl_syms + br_syms)
    out = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f'<!-- vine-decor.svg — GENERATED by Toolbox/Python/planter-extract.py '
        f'(BL=planter{bl_n}, BR=planter{br_n}).\n'
        '     White-line skeletons extracted from the planter Shape layers; the offset\n'
        '     shimmer layer is added by builder_common.vine_decor() as duplicate <use>\n'
        '     elements stroked with the host-document shimmer gradients.\n'
        '     Strokable elements carry pathLength="100" for the one-rule dash growth.\n'
        '     Regenerate with a different combo: planter-extract.py <bl_n> <br_n> -->\n'
        '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"\n'
        '     width="0" height="0">\n\n'
        f'{body}\n\n</svg>\n'
    )
    dest = SVG_DIR / 'vine-decor.svg'
    dest.write_text(out, encoding='utf-8')
    print(f'Wrote {dest} ({len(out):,} bytes)  BL viewBox={bl_vb}  BR viewBox={br_vb}')


if __name__ == '__main__':
    main()
